### ISSUE TITLE
publish workflow always runs

### ISSUE THREAD

**Issue by taciturnaxolotl** [EnhancedJax/Bagels#45]
hi!!! I noticed that your workflow was failing because a release already exists so I was wondering if you maybe want to change the trigger to on release? Awesome project btw; I'm going to take a stab at packaging for nix latter today :)

```yaml
on:
  release:
    types: [published]
    branches: [master]
```
