### ISSUE TITLE
Add configurable layouts with resizing and reordering options

### ISSUE THREAD

**Issue by mzfr** [EnhancedJax/Bagels#49]
I think it would be a nice feature to let users customize their layouts in Bagels. 

Users would be able to adjust both the size of sections (like making the records column smaller) and their arrangement (like moving accounts to the bottom).

I think we can achieve this in two ways: component sizing could be handled through tcss configurations, while component reordering would need changes to the `compose()` method in `home.py`. 

An example would be:

```
layout:
  sizes:
    left_column: 60%
    right_column: 40%
    insights_height: 30%
  order:
    left:
      - date_mode
      - insights
      - accounts
    right:
      - templates
      - records
```
